{
  "comments": [
    {
      "key": {
        "uuid": "d56910ac_b1d1fe57",
        "filename": "test/unit/lib/bdev/vbdev_lvol.c/vbdev_lvol_ut.c",
        "patchSetId": 68
      },
      "lineNbr": 888,
      "author": {
        "id": 1011262
      },
      "writtenOn": "2018-02-07T10:08:40Z",
      "side": 1,
      "message": "This one should fail as lvol2 do not have this name - lvol does have. We should check that fail. We can also add same command below for lvol and then try to rename lvol2 again to \"new_lvol_name\" and check that this time it will succeeded.",
      "range": {
        "startLine": 888,
        "startChar": 1,
        "endLine": 888,
        "endChar": 70
      },
      "revId": "7b252081b544e00efeab49f2841f29948b6f3c46",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}