{
  "comments": [
    {
      "key": {
        "uuid": "570a136c_9eacede1",
        "filename": "lib/vhost/vhost.c",
        "patchSetId": 1
      },
      "lineNbr": 894,
      "author": {
        "id": 1011218
      },
      "writtenOn": "2017-10-17T14:34:47Z",
      "side": 1,
      "message": "there\u0027s no way to recover from this error, so the abort() here seemed reasonable.\nwhat\u0027s the reason behind this change?",
      "range": {
        "startLine": 894,
        "startChar": 2,
        "endLine": 894,
        "endChar": 9
      },
      "revId": "9a23bb06f952ad1be2b9750f0515ac890317b4c2",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}